# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

[project]
name = "sandbox"
version = "0.0.1"
requires-python = ">= 3.13"
dependencies = [
  "ptpython",
  "ipython",
  "rich", # https://github.com/Textualize/rich
]
